#!/usr/bin/bash

set -eoux pipefail

if command -v dnf5 >/dev/null 2>&1; then
	dnf5 clean all
elif command -v microdnf >/dev/null 2>&1; then
	microdnf clean all
fi
rm -rf /tmp/* || true
rm -rf /var/log/dnf5.log || true
rm -rf /var/log/dnf.log || true
rm -rf /boot/* || true
rm -rf /boot/.* || true

ostree container commit
