#!/usr/bin/bash

set -eoux pipefail

if command -v dnf5 >/dev/null 2>&1; then
	dnf5 clean all
elif command -v microdnf >/dev/null 2>&1; then
	microdnf clean all
fi
rm -rf /tmp/* || true
for path in /var/lib /var/roothome /var/run /var/tmp; do
	if [[ -e "${path}" ]]; then
		rm -rf "${path}"
	fi
done
if [[ -d /var/cache ]]; then
	find /var/cache -mindepth 1 -maxdepth 1 -type d \! -name libdnf5 \! -name rpm-ostree -exec rm -fr {} \;
fi
mkdir -p /var/tmp
chmod -R 1777 /var/tmp

if [[ "${BASE_IMAGE_NAME:-}" == "centos-stream-10" || "${BASE_IMAGE_NAME:-}" == "rhel-10" ]]; then
	exit 0
fi

ostree container commit
