FROM quay.io/centos/centos:stream10

RUN dnf -y install python3 && \
    dnf clean all

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod 0755 /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
